In [1]:
import numpy as np

## Datatypes and Attributes

In [4]:
#This is a numpy ndarray n dimensional array, the first one i 1 dimensional
a1 = np.array([1, 2, 4])
a1

array([1, 2, 4])

In [5]:
#2 dimensional array
a2 = np.array([[1,2,3],
               [2.3,5,6]])
a2

array([[1. , 2. , 3. ],
       [2.3, 5. , 6. ]])

In [9]:
#3 dimensional array
a3 = np.array([[[1,2,3],
                [2,3,4]],
               [[3,4,5],
                [4,5,6]],
               [[5,6,7],
                [6,7,8]]])
a3.shape

(3, 2, 3)

In [15]:
#return n dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# return the n element of the array
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
#type of array 
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
#Create a Dataframe from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  2.3  5.0  6.0

In [23]:
a3 = np.zeros((3,3))
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Creating arrays

In [28]:
#Array fill with 1, we can choose the data type of the array by setting it with dtype
one = np.ones((2,3), dtype=int)

In [29]:
one

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
range = np.arange(0,100,3)
range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [32]:
random = np.random.randint(0,10,size=(3,3))
random

array([[3, 0, 0],
       [4, 3, 7],
       [0, 2, 8]])

In [35]:
#Random arrays with floating numbers
random2 = np.random.random((5,2))
random2

array([[0.10782504, 0.00746688],
       [0.2579299 , 0.01309173],
       [0.74992692, 0.23742636],
       [0.58885272, 0.54223821],
       [0.31735082, 0.94105114]])

In [37]:
random3 = np.random.rand(5,3)
random3

array([[0.05554177, 0.15962279, 0.96733508],
       [0.67934289, 0.83316762, 0.90756308],
       [0.89732248, 0.91102022, 0.63175136],
       [0.45387606, 0.63866123, 0.61146734],
       [0.65523641, 0.36490772, 0.10780592]])

##  Viewing arrays and matrices

In [39]:
np.unique(random)

array([0, 2, 3, 4, 7, 8])

In [40]:
a1

array([1, 2, 4])

In [41]:
a1[0]

1

In [42]:
a2

array([[1. , 2. , 3. ],
       [2.3, 5. , 6. ]])

In [43]:
a2[0]

array([1., 2., 3.])

In [46]:
a2[0][1]

2.0

In [49]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[1, 6, 9, 9, 7],
         [3, 5, 1, 9, 1],
         [0, 0, 0, 2, 9],
         [6, 1, 2, 2, 2]],

        [[9, 7, 2, 8, 9],
         [2, 7, 4, 7, 6],
         [3, 3, 2, 9, 8],
         [6, 6, 7, 9, 9]],

        [[6, 3, 1, 1, 3],
         [4, 3, 2, 5, 9],
         [1, 8, 6, 4, 5],
         [1, 3, 6, 2, 4]]],


       [[[3, 3, 5, 8, 1],
         [8, 0, 4, 7, 1],
         [4, 6, 9, 6, 5],
         [7, 6, 3, 0, 6]],

        [[3, 0, 8, 1, 7],
         [6, 2, 3, 3, 7],
         [0, 4, 3, 1, 9],
         [9, 5, 9, 8, 2]],

        [[7, 0, 4, 3, 1],
         [2, 5, 9, 9, 4],
         [5, 4, 0, 9, 6],
         [4, 9, 0, 5, 8]]]])

In [52]:
a4[:, :3, :1, :5,]

array([[[[1, 6, 9, 9, 7]],

        [[9, 7, 2, 8, 9]],

        [[6, 3, 1, 1, 3]]],


       [[[3, 3, 5, 8, 1]],

        [[3, 0, 8, 1, 7]],

        [[7, 0, 4, 3, 1]]]])

## Manipulating arrays

### Arithmetic

In [53]:
a1, one

(array([1, 2, 4]),
 array([[1, 1, 1],
        [1, 1, 1]]))

In [54]:
a1 + one

array([[2, 3, 5],
       [2, 3, 5]])

In [55]:
a1 * one

array([[1, 2, 4],
       [1, 2, 4]])

In [60]:
a3 = np.array([[[1,2,3],
                [2,3,4],
                [3,4,5]],
                [[4,5,6],
                [5,6,7],
                [6,7,8]]])

In [62]:
#a3 * a2 error there are not compatibile
# How to re shape an array?

In [64]:
a1 / one

array([[1., 2., 4.],
       [1., 2., 4.]])

In [65]:
a1 / a2

array([[1.        , 1.        , 1.33333333],
       [0.43478261, 0.4       , 0.66666667]])

In [66]:
# Floor division goes with 2 slash
a1 // a2

array([[1., 1., 1.],
       [0., 0., 0.]])

In [67]:
a1 ** a2

array([[1.000e+00, 4.000e+00, 6.400e+01],
       [1.000e+00, 3.200e+01, 4.096e+03]])

In [68]:
a1 % a2

array([[0., 0., 1.],
       [1., 2., 4.]])

In [69]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 54.59815003])

In [70]:
np.log(a1)

array([0.        , 0.69314718, 1.38629436])